### ISSUE TITLE
revert text-decoration-thickness

### ISSUE THREAD

**Issue by dwhieb** [dwhieb/flexbox-reset#17]
```css
a:link {
  text-decoration-thickness: revert; (maybe "from-font"?)
}
```
