### ISSUE TITLE
text overflow

### ISSUE THREAD

**Issue by dwhieb** [dwhieb/flexbox-reset#18]
```css
blockquote, dd, dt, figcaption, p, h1, h2, h3, h4, h5, h6, li {
  overflow-wrap: break-word;
}
```
