### ISSUE TITLE
inherit box-sizing

### ISSUE THREAD

**Issue by dwhieb** [dwhieb/flexbox-reset#19]
```css
*,
*::before,
*::after {
  box-sizing: inherit;
}

html {
  box-sizing: border-box;
}
```
